package edu.traning.web.controller;

public enum CommandName {

    WRONG_REQUEST,
    GO_TO_REGISTRATION,
    GO_TO_AUTHORIZATION,
    GO_TO_INDEX_PAGE,
    GO_TO_ABOUT_US,
    GO_TO_CLINICS,
    GO_TO_CLINIC_INFO,
    GO_TO_USER_PROFILE,
    GO_TO_ADMIN_PROFILE,
    GO_TO_DOCTORS,
    GO_TO_DOCTOR_INFO,
    DO_AUTH,
    DO_REGISTRATION,
    SEARCH_CLINIC,
    SEARCH_DOCTOR,
    NEW_USER_REGISTRATION,
    LOGOUT_FROM_ACCOUNT,
    ADD_CLINIC,
    ADD_FOOTER,
    ADD_NEWS,
    ADD_DOCTOR,
    DELETE_CLINIC,
    DELETE_DOCTOR,
    DELETE_FOOTER,
    DELETE_NEWS,
    UPDATE_ABOUT,
    UPDATE_NEWS,
    UPDATE_CLINIC,
    UPDATE_DOCTOR,
    UPDATE_FOOTER,
    UPDATE_USER

}