package edu.traning.web.controller;

public enum CommandName {

    DO_AUTH,
    DO_REGISTRATION,
    GO_TO_REGISTRATION,
    WRONG_REQUEST,
    GO_TO_AUTHORIZATION,
    GO_TO_INDEX_PAGE,
    GO_TO_ABOUT_US,
    GO_TO_CLINICS,
    GO_TO_CLINIC_INFO,
    SEARCH_CLINIC,
    NEW_USER_REGISTRATION,
    GO_TO_USER_PROFILE,
    GO_TO_ADMIN_PROFILE,
    FUNCTION_ADMIN_PROFILE

}